### ISSUE TITLE
Partial namespace included in verified file name

### ISSUE THREAD

**Issue by benmccallum** [SimonCropp/Verify#63]
for multipart namespaces (eg `Foo.Bar.Bat`) part of the namespace is being correctly included in the verified file name. Once upgrading to 1.27.0 all existing files, with incorrect names, will be renames to the correct file name.

**Comment by benmccallum** [comment]
Perhaps it's as simple as adding a method in [VerifySettings](https://github.com/SimonCropp/Verify/blob/master/src/Verify/Naming/VerifySettings.cs) like `ExcludeNamespace` and then working that through, but testName comes all the way down from VerifyBase by the looks, so maybe if I could tap in there? Could you expose a virtual method `ModifyTestName` or something there that's a no-op for you but would let me modify it?

**Comment by benmccallum** [comment]
Tried getting around it with some funky exclude and include .csproj stuff to try and rewrite the file name, and it would've worked, but the project can't load the file since it's path is too long for Windows...

**Comment by SimonCropp** [comment]
> Perhaps it's as simple as adding a method in VerifySettings like ExcludeNamespace

i dont think namespace is included?

what convention would you use. 

once thing we could do is have `received` => `r` and `verified` => `v`

**Comment by SimonCropp** [comment]
i just added a namespace to a test and it did not appear in the verified file names. so i think that is a bug https://github.com/SimonCropp/Verify/commit/2f6488392cc253ec8b715326c0ddab053983cb83

can u share a repro?

**Comment by benmccallum** [comment]
Hey sorry I've just logged off for the day. I'll make a repro when I get a sec. 

I ended up working around it by hacking together a `MyVerifyBase` and building up the testName passed through to the verifier myself.  The issue I found was that the Context.TestMethod...Class.Name was returning the whole namespace as well. I did a dodgy substring from last . + 1 to trim the start off. 

I might have a weird setup of projects, I'll do a basic repro this wkend hopefully

**Comment by benmccallum** [comment]
Hey @SimonCropp, I've been able to repro. 

I thought it could be a weirdness I have where I've got a 3.1 test app targeting a 2.2 project to test, but confirmed that's not the case as it occurs in a 2.2 test project too. 

Repro is essentially a netcoreapp test project pointing at a netstandard2.2 project to test, where there's nested folder structures followed in both projects. 

Interestingly the generated file name excludes the first part of the namespace. e.g. `System.Under.Test.With.Some.Nesting...` becomes `Under.Test.With.Some.Nesting...`. 

[verify-xunit-repro.zip](https://github.com/SimonCropp/Verify/files/4397340/verify-xunit-repro.zip)

**Comment by benmccallum** [comment]
Here's a git patch file you can apply to your latest master to see it repro'd in a similar way to the test you'd added. That being said, it could be my machine, so let me know if you need certain details. I'm on latest VS, 16.5.1.
[0001-Repro.zip](https://github.com/SimonCropp/Verify/files/4397368/0001-Repro.zip)

**Comment by SimonCropp** [comment]
thanks for the patch. it is a bug. see update description

**Comment by benmccallum** [comment]
Champion! Thanks!
