### ISSUE TITLE
Tests pass when they should fail

### ISSUE THREAD

**Issue by benmccallum** [SimonCropp/Verify#69]
#### Describe the bug

Running tests, the comparison tool is launched and the diff clearly shows that the verified vs received are different, but for some reason the tests pass. 

 * Visual Studio - 16.5.1
 * dotnet --version = 3.1.200
 * Project file is netcoreapp3.1 with:
  * xunit 2.4.1 (and vs runner)
  * Verify.xunit 1.27.0

#### Minimal Repro

Raising for now, will do when I can.

#### Submit a PR that fixes the bug

Raising for now, will do when I can.

**Comment by benmccallum** [comment]
Hmm, I think this might be because I'm not returning the result of Verify as part of the test method. Will check that now.

**Comment by SimonCropp** [comment]
u need to await or return the task

**Comment by benmccallum** [comment]
haha yep, realised as soon as I posted. Knew I was missing something stupid. Old assert/should habits die hard. Sorry!
