### ISSUE TITLE
Issue with Verify creating empty file

### ISSUE THREAD

**Issue by benmccallum** [SimonCropp/Verify#96]
#### Preamble

 * Visual Studio - 16.5.4
 * dotnet - 3.1.latest
 * Verify.Xunit

Full refs on the test project:
![image](https://user-images.githubusercontent.com/157336/79882744-55eb5880-83f3-11ea-9389-4b8de587b918.png)

#### Describe the bug

Running the test fails. 
* Seems to create the *.received.txt file 
* Interestingly, if I rename the *.received.txt to *.verified.txt, the test the passes.

So my guess is it's choking trying to create the empty verified one, which the stack trace certainly attests to.
* Note, I went looking into that .nuget packages path, and what struck me as odd is the path it can't find a part of is:
* `C:\Users\Developer\.nuget\packages\emptyfiles\2.0.1\lib\netstandard2.0\EmptyFiles`
But the file it could be looking for is:
* `C:\Users\Developer\.nuget\packages\emptyfiles\2.0.1\lib\netstandard2.0\EmptyFiles.dll`

i.e. it's a dll not a folder.

```
    System.TypeInitializationException : The type initializer for 'EmptyFiles.AllFiles' threw an exception.
    ---- System.IO.DirectoryNotFoundException : Could not find a part of the path 'C:\Users\Developer\.nuget\packages\emptyfiles\2.0.1\lib\netstandard2.0\EmptyFiles'.
  Stack Trace: 
    AllFiles.TryCreateFile(String path, Boolean useEmptyStringForTextFiles) line 209
    DiffRunner.Launch(ResolvedDiffTool diffTool, String tempFile, String targetFile) line 79
    DiffRunner.Launch(String tempFile, String targetFile) line 65
    VerifyEngine.ProcessMissing(StringBuilder builder, FilePair item) line 278
    VerifyEngine.ProcessMissing(StringBuilder builder) line 238
    VerifyEngine.ThrowIfRequired(String message) line 123
    InnerVerifier.Verify(String input, VerifySettings settings) line 25
    InnerVerifier.Verify[T](T input, VerifySettings settings) line 43
    --- End of stack trace from previous location where exception was thrown ---
    ----- Inner Stack Trace -----
    FileSystemEnumerator`1.CreateDirectoryHandle(String path, Boolean ignoreNotFound)
    FileSystemEnumerator`1.ctor(String directory, EnumerationOptions options)
    FileSystemEnumerable`1.ctor(String directory, FindTransform transform, EnumerationOptions options)
    FileSystemEnumerableFactory.UserFiles(String directory, String expression, EnumerationOptions options)
    Directory.InternalEnumeratePaths(String path, String searchPattern, SearchTarget searchTarget, EnumerationOptions options)
    Directory.EnumerateFiles(String path, String searchPattern, SearchOption searchOption)
    AllFiles.cctor() line 63
```

#### Minimal Repro

Incoming when I get a moment. 

#### Submit a PR that fixes the bug

Incoming when I get a moment.

**Comment by SimonCropp** [comment]
can u try 1.34

**Comment by benmccallum** [comment]
👌 thanks mate. Sorry I didn't repro or PR, been smashed trying to get a few big things out so when I had a workaround I just logged and moved on. Appreciate the fix!
